# Generated by Django 5.2.4 on 2025-07-14 17:31

import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[apps.products.validators.validate_image_file_extension, apps.products.validators.validate_image_file_size]),
        ),
    ]
