# Generated by Django 5.2.4 on 2025-07-14 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_delete_product'),
        ('products', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category'),
        ),
        migrations.RemoveField(
            model_name='productimagegallery',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productvariantimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariantimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproductimage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductImageGallery',
        ),
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
        migrations.DeleteModel(
            name='UserProductImage',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='dominant_colors',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='width',
        ),
    ]
