# Generated by Django 5.2.4 on 2025-07-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
